version = 0.1

[ci.deploy.parameters]
stack_name = "nb-bootstrap"
s3_bucket = "sam-artifacts-542768766351-us-west-1-main"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false